### ISSUE TITLE
If you have a typo in the backend, you are lost

### ISSUE THREAD

**Issue by amenk** [fbrnc/Aoe_DesignFallback#8]
Problem: Enter something wrong. Exception is thrown:

<pre>
Line must contain package and theme separated by ":"

#0 /home/me/local-workspace/shop/public/app/code/community/Aoe/DesignFallback/Model/Design/Package.php(29): Mage::throwException('Line must conta...')
#1 /home/me/local-workspace/shop/public/app/code/community/Aoe/DesignFallback/Model/Design/Package.php(15): Aoe_DesignFallback_Model_Design_Package->getFallbackScheme(Array)
#2 /home/me/local-workspace/shop/public/app/code/core/Mage/Core/Model/Design/Package.php(425): Aoe_DesignFallback_Model_Design_Package->_fallback('translate.csv', Array, Array)
#3 /home/me/local-workspace/shop/public/app/code/core/Mage/Core/Model/Design/Package.php(454): Mage_Core_Model_Design_Package->getFilename('translate.csv', Array)
#4 /home/me/local-workspace/shop/public/app/code/core/Mage/Core/Model/Translate.php(277): Mage_Core_Model_Design_Package->getLocaleFileName('translate.csv')
#5 /home/me/local-workspace/shop/public/app/code/core/Mage/Core/Model/Translate.php(141): Mage_Core_Model_Translate->_loadThemeTranslation(false)
#6 /home/me/local-workspace/shop/public/app/code/core/Mage/Core/Model/App/Area.php(146): Mage_Core_Model_Translate->init('adminhtml')
#7 /home/me/local-workspace/shop/public/app/code/core/Mage/Core/Model/App/Area.php(121): Mage_Core_Model_App_Area->_initTranslate()
#8 /home/me/local-workspace/shop/public/app/code/core/Mage/Core/Model/App/Area.php(93): Mage_Core_Model_App_Area->_loadPart('translate')
#9 /home/me/local-workspace/shop/public/app/code/core/Mage/Core/Model/App.php(774): Mage_Core_Model_App_Area->load()
</pre>

now the admin interface itself does not work any more .. there should be some pre validation so we have a chance to fix it, which diving into the database...

**Comment by easingthemes** [comment]
How to fix this? I deleted all lines and got this error.

**Comment by easingthemes** [comment]
in table core_config_data
find design/fallback/fallback
add value base:default

**Comment by royduin** [comment]
I ran into the same problem, but with setting up my store with an install/script script. Maybe a idea to replace
`$configuration = Mage::getStoreConfig('design/fallback/fallback', $this->getStore())`
with: 
`$configuration = Mage::getStoreConfig('design/fallback/fallback', $this->getStore()) ?: "[current]:[current]\n[current]:default\nbase:default";`
In the `app\code\local\Aoe\DesignFallback\Model\Design\Package.php` file?
